# Generated by Django 4.2.4 on 2023-08-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("address_two", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "trade_license",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
