# Generated by Django 4.2.4 on 2023-08-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_rename_deviceddelegate_devicedelegate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceReceived",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("check_out", models.DateTimeField()),
                ("device_check_out_condition", models.TextField()),
                ("return_date", models.DateTimeField()),
                ("device_return_condition", models.TextField()),
                (
                    "delegated_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_device",
                        to="organization.devicedelegate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
